---
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: .
    ldflags:
      - "-X github.com/veerendra2/gopackages/version.Version={{.Version}}"
      - "-X github.com/veerendra2/gopackages/version.Revision={{.ShortCommit}}"
      - "-X github.com/veerendra2/gopackages/version.Branch={{.Branch}}"
      - "-X github.com/veerendra2/gopackages/version.BuildUser={{envOrDefault 'USER' 'ci'}}"
      - "-X github.com/veerendra2/gopackages/version.BuildDate={{.Date}}"

archives:
  - formats: ["zip"]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: symlinkr
    repository:
      owner: veerendra2
      name: homebrew-tap
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/veerendra2/symlinkr"
    description: "Declarative symlink management for dotfiles."
    license: "Apache"
